version: '3'

services:
  mdb:
    image: mongo:3.4.3
    command: mongod
  bdb:
    depends_on:
      - mdb
      - tendermint
    ports:
      - "46658"
    build:
      context: .
      dockerfile: ./compose/travis/Dockerfile
      args:
        backend: localmongodb
    volumes:
      - .:/usr/src/app/
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mdb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_START_TENDERMINT: 0
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 46657
    command: bash -c "sleep 3600"
  tendermint:
    image: tendermint/tendermint:0.12
    ports:
      - "46657"
      - "46656"
    volumes:
      - ./tmdata/config.toml:/tendermint/config.toml
    entrypoint: ["/bin/bash", "-c", "tendermint init && tendermint node"]
