# This file is used to bring up a single node
# development and test environment with Bigchain,
# MongoDB and Tendermint
#
# 'bdb-base' service is only used to build the 'bigchaindb'
# base image which is then used by 'bdb' service to build a
# development image. Having a base image with all dependencies
# already installed helps reduce build time of development image
# significantly

version: '3'

services:
  mdb:
    image: mongo:3.4.3
    ports:
      - "27017"
    command: mongod
  bdb-base:
    image: bigchaindb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        backend: localmongodb
    volumes:
      - ./bigchaindb:/usr/src/app/bigchaindb
      - ./tests:/usr/src/app/tests
  bdb:
    depends_on:
      - mdb
      - tendermint
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./bigchaindb:/usr/src/app/bigchaindb
      - ./tests:/usr/src/app/tests
    environment:
      BIGCHAINDB_DATABASE_HOST: mdb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_START_TENDERMINT: 0
      TENDERMINT_HOST: tendermint
      TENDERMINT_PORT: 46657
    ports:
      - 9984:9984
    command: bigchaindb -l DEBUG start
  tendermint:
    image: tendermint/tendermint
    volumes:
      - ./tmdata:/tendermint
    entrypoint: ''
    command: bash -c "tendermint unsafe_reset_all && tendermint node"
