FROM python:3.6
LABEL maintainer "dev@bigchaindb.com"

RUN apt-get update \
    && apt-get install -y vim \
    && pip install -U pip \
    && pip install pynacl \
    && apt-get autoremove \
    && apt-get clean
