#####################################################################
# TODO This YAML file desribes a ConfigMap with the FQDN of the mongo    #
# instance to be started. MongoDB instance uses the value from this #
# ConfigMap to bootstrap itself during startup.                     #
#####################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-whitelist
  namespace: default
data:
  # ':' separated list of allowed hosts
  allowed-hosts: 95.91.241.60/16:192.168.0.1/16
