apiVersion: v1
kind: Service
metadata:
  name: ngx-svc
  namespace: default
  labels:
    name: ngx-svc
  annotations:
    # NOTE: the following annotation is a beta feature and
    # only available in GCE/GKE and Azure as of now
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    app: ngx-dep 
  ports:
  - port: 27017
    targetPort: 27017
    name: ngx-public-mdb-port
    protocol: TCP
  - port: 80
    targetPort: 80
    name: ngx-public-bdb-port
    protocol: TCP
  type: LoadBalancer
