#########################################################################
# This YAML file desribes a ConfigMap with a valid list of IP addresses #
# that can connect to the MongoDB instance.                             #
#########################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-whitelist
  namespace: default
data:
  allowed-hosts: ""
