apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openresty-instance-1-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openresty-instance-1-dep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx-openresty
        image: bigchaindb/nginx_3scale:unstable
        imagePullPolicy: Always
        env:
        - name: THREESCALE_PORTAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: apicast-secret
              key: portal-endpoint
        - name: RESOLVER
          valueFrom:
            configMapKeyRef:
              name: vars
              key: cluster-dns-server-ip
        - name: APICAST_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: apicast-config
              key: api-log-level
        - name: APICAST_MANAGEMENT_API
          valueFrom:
            configMapKeyRef:
              name: apicast-config
              key:  mgmt-api-mode
        - name: BIGCHAINDB_BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: vars
              key: bdb-instance-name
        - name: BIGCHAINDB_API_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: bigchaindb-api-port
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8090
          protocol: TCP
